from app.tui.commands import (
    COMPRESS_COMMAND_LITERAL,
    MCP_COMMAND_PREFIX,
    MODEL_COMMAND_PREFIX,
    NEW_COMMAND_LITERAL,
    RESET_COMMAND_LITERAL,
    SKILLS_COMMAND_LITERAL,
    SPAWN_COMMAND_LITERAL,
    STOP_COMMAND_LITERAL,
)

HELP_COMMAND_LITERAL = "\\help"

AVAILABLE_COMMANDS = [
    NEW_COMMAND_LITERAL,
    RESET_COMMAND_LITERAL,
    COMPRESS_COMMAND_LITERAL,
    MODEL_COMMAND_PREFIX.strip() + " <model>",
    SPAWN_COMMAND_LITERAL,
    MCP_COMMAND_PREFIX.strip() + " <url>",
    SKILLS_COMMAND_LITERAL,
    STOP_COMMAND_LITERAL,
    HELP_COMMAND_LITERAL,
]


def format_available_commands() -> str:
    return "\n".join(AVAILABLE_COMMANDS)
